theme: jekyll-theme-hacker
author: Alexandru Popescu
title: AltPope's GitHub homepage
description: You'll find here a mishmash of personal projects
social_links: 
  linkedin: alexandru-popescu-8365271
